"""Add tour images table

Revision ID: 27b78a354745
Revises: e0990ba50dbc
Create Date: 2025-09-18 17:54:38.665366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b78a354745'
down_revision = 'e0990ba50dbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###