"""add_tour_images_table

Revision ID: 490a1e813584
Revises: 27b78a354745
Create Date: 2025-09-18 18:02:53.919296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490a1e813584'
down_revision = '27b78a354745'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###